package pear2pear;

import java.io.*;
import java.net.*;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Scanner;

public class Pear {

    private static final int PORT = 5000;
    private static final int BUFFER_SIZE = 4096;

    /***
     * Start the server or client based on command line arguments.
     * @param args Command line arguments: "server" to start server, "client <host>" to start client.
     * @throws IOException
     */
    public static void main(String[] args) throws IOException {

        if (args.length == 0) {
            System.out.println("Usage: java pear2pear/Pear.java [server|client <host>]");
            return;
        }

        if (args[0].equalsIgnoreCase("server")) {
            startServer();
        } else if (args[0].equalsIgnoreCase("client")) {
            if (args.length < 2) {
                System.out.println("Usage: java pear2pear/Pear.java client <host>");
                return;
            }
            startClient(args[1]);
        }

    }

    /***
     * Starts the server, listens for a client connection, and sends a file.
     * @throws IOException
     */
    private static void startServer() throws IOException {

        Scanner sc = new Scanner(System.in);
        System.out.print("Path to file: ");
        String path = sc.nextLine();
        File file = new File(path);

        if (!file.exists() || !file.isFile()) {
            System.out.println("File does not exist.");
            return;
        }

        String passkey = generatePasskey();

        ServerSocket serverSocket = new ServerSocket(PORT);
        System.out.println("Server listening on port " + PORT + " at " + InetAddress.getLocalHost().getHostAddress());
        System.out.println("Passkey: " + passkey + " (share with the client)");

        Socket socket = serverSocket.accept();

        DataInputStream dis = new DataInputStream(socket.getInputStream());
        DataOutputStream dos = new DataOutputStream(socket.getOutputStream());

        if (!serverAuthenticate(dis, dos, passkey)) {
            System.out.println("Authentication failed. Closing connection.");
            socket.close();
            serverSocket.close();
            return;
        }

        sendFile(file, dos);
        socket.close();
        serverSocket.close();

    }

    /***
     * Starts the client, connects to the server, and receives a file.
     * @param host The hostname or IP address of the server to connect to.
     * @throws IOException
     */
    private static void startClient(String host) throws IOException {

        Scanner sc = new Scanner(System.in);
        System.out.print("Folder path to save file: ");
        String savePath = sc.nextLine();
        File saveDir = new File(savePath);

        if (!saveDir.exists() || !saveDir.isDirectory()) {
            System.out.println("Invalid folder path.");
            return;
        }

        Socket socket = new Socket(host, PORT);
        System.out.println("Connected to server: " + host);

        DataInputStream dis = new DataInputStream(socket.getInputStream());
        DataOutputStream dos = new DataOutputStream(socket.getOutputStream());

        if (!clientAuthenticate(dis, dos)) {
            System.out.println("Authentication failed.");
            socket.close();
            return;
        }

        receiveFile(dis, saveDir);
        socket.close();

    }

    /***
     * Generates a random passkey for authentication.
     * The passkey is a 12-byte random value encoded as a 16-character Base64
     * @return
     */
    private static String generatePasskey() {

        byte[] bytes = new byte[12];
        new SecureRandom().nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);

    }

    /***
     * Authenticates the client by checking the provided passkey against the server's passkey.
     * The server expects the first message from the client to be the passkey.
     * @param dis
     * @param dos
     * @param passkey
     * @return
     * @throws IOException
     */
    private static boolean serverAuthenticate(DataInputStream dis, DataOutputStream dos, String passkey) throws IOException {

        String provided = dis.readUTF();
        boolean ok = passkey.equals(provided);
        dos.writeUTF(ok ? "AUTH_OK" : "AUTH_FAIL");
        dos.flush();
        return ok;

    }

    /***
     * Authenticates the client by prompting for a passkey.
     * The client must enter the passkey that was generated by the server.
     * @param dis
     * @param dos
     * @return
     * @throws IOException
     */
    private static boolean clientAuthenticate(DataInputStream dis, DataOutputStream dos) throws IOException {

        Scanner sc = new Scanner(System.in);
        System.out.print("Enter passkey: ");
        String passkey = sc.nextLine().trim();
        dos.writeUTF(passkey);
        dos.flush();
        String res = dis.readUTF();
        return "AUTH_OK".equals(res);

    }

    /***
     * Sends a file to the connected client.
     * @param file The file to send.
     * @param dos
     * @throws IOException
     */
    private static void sendFile(File file, DataOutputStream dos) throws IOException {
        dos.writeUTF(file.getName());
        dos.writeLong(file.length());

        try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
            byte[] buffer = new byte[BUFFER_SIZE];
            int bytesRead;
            while ((bytesRead = bis.read(buffer)) != -1) {
                dos.write(buffer, 0, bytesRead);
            }
            dos.flush();
            System.out.println("File sent.");
        }
    }

    /***
     * Receives a file from the server and saves it to the specified directory.
     * The file name and size are read from the input stream, and the file is saved
     * in the specified directory.
     * @param dis
     * @param saveDir Directory path where the file will be saved.
     * @throws IOException
     */
    private static void receiveFile(DataInputStream dis, File saveDir) throws IOException {

        String fileName = dis.readUTF();
        long fileSize = dis.readLong();
        File newFile = new File(saveDir, fileName);

        try (BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(newFile))) {
            byte[] buffer = new byte[BUFFER_SIZE];
            int bytesRead;
            long totalRead = 0;
            while (totalRead < fileSize && (bytesRead = dis.read(buffer, 0, (int) Math.min(buffer.length, fileSize - totalRead))) != -1) {
                bos.write(buffer, 0, bytesRead);
                totalRead += bytesRead;
            }
            bos.flush();
            System.out.println("File received and saved as " + newFile.getAbsolutePath());
        }

    }

}